# This file contains custom configuration for the Siklid application.
parameters:
  postman:
    directory: '%kernel.project_dir%/docs/postman'
    src: '%kernel.project_dir%/docs/postman/v1.yml'
    dist: '%kernel.project_dir%/docs/postman/v1.dist.yml'

services:
  Symfony\Component\Finder\Finder:
    class: Symfony\Component\Finder\Finder
