# This file contains custom configuration for the Siklid application.
parameters:
  postman:
    directory: '%kernel.project_dir%/docs/postman'
    src: '%kernel.project_dir%/docs/postman/v1.yaml'
    dist: '%kernel.project_dir%/docs/postman/dist/v1.json'

services:
  Symfony\Component\Finder\Finder:
    class: Symfony\Component\Finder\Finder

  Symfony\Component\Yaml\Parser:
    class: Symfony\Component\Yaml\Parser

  App\Foundation\Service\Storage\LocalStorage: ~
  App\Foundation\Service\Storage\StorageInterface: '@App\Foundation\Service\Storage\LocalStorage'
